# Generated by Django 5.1.3 on 2024-11-22 00:29

import doctor.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_marcamedicamento_options_alter_doctor_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[doctor.utils.valida_cedula], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[doctor.utils.valida_cedula], verbose_name='Cédula'),
        ),
    ]
