# Generated by Django 5.1.3 on 2024-11-22 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sábado', 'Sábado'), ('domingo', 'Domingo')], max_length=10, unique=True, verbose_name='Día de la Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('Intervalo_desde', models.TimeField(verbose_name='Intervalo desde')),
                ('Intervalo_hasta', models.TimeField(verbose_name='Intervalo Hasta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Horario de Atención Doctor',
                'verbose_name_plural': 'Horarios de Atención de los Doctores',
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Atención')),
                ('presion_arterial', models.CharField(blank=True, max_length=20, null=True, verbose_name='Presión Arterial')),
                ('pulso', models.IntegerField(blank=True, null=True, verbose_name='Pulso (ppm)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia Respiratoria(rpm)')),
                ('saturacion_oxigeno', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Saturación de Oxígeno (%)')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Altura (m)')),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de Consulta')),
                ('sintomas', models.TextField(verbose_name='Sintomas')),
                ('tratamiento', models.TextField(verbose_name='Plan de Tratamiento')),
                ('examen_fisico', models.TextField(blank=True, null=True, verbose_name='Examen Físico')),
                ('comentario_adicional', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('diagnostico', models.ManyToManyField(related_name='diagnosticos_atencion', to='core.diagnostico', verbose_name='Diagnósticos')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctores_atencion', to='core.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Atención',
                'verbose_name_plural': 'Atenciones',
                'ordering': ['-fecha_atencion'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('tipo_certificado', models.CharField(max_length=100, verbose_name='Tipo de Certificado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('diagnostico', models.ManyToManyField(related_name='certificados_diagnosticos', to='core.diagnostico', verbose_name='Diagnósticos')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor', verbose_name='Doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
        migrations.CreateModel(
            name='CostosAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_consulta', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Costo de la Consulta')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de los Costos')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Pago')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos', to='attention.atencion')),
            ],
            options={
                'verbose_name': 'Costo de Atención',
                'verbose_name_plural': 'Costos de Atención',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='ExamenSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_examen', models.CharField(max_length=255, verbose_name='Nombre del Examen')),
                ('fecha_solicitud', models.DateField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo del Examen')),
                ('resultado', models.FileField(blank=True, null=True, upload_to='resultados_examenes/', verbose_name='Resultado del Examen')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('estado', models.CharField(choices=[('S', 'Solicitado'), ('R', 'Realizado')], max_length=20, verbose_name='Estado del Examen')),
                ('atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examenes', to='attention.atencion', verbose_name='Atención Médica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examenes', to='core.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Examen Médico',
                'verbose_name_plural': 'Exámenes Médicos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('prescripcion', models.TextField(verbose_name='Prescripción')),
                ('duracion_tratamiento', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración del Tratamiento (días)')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='attention.atencion', verbose_name='Atención')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_atencion', to='core.medicamento', verbose_name='Medicamento')),
                ('examen_solicitado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_atencion', to='attention.examensolicitado', verbose_name='Examen Solicitado')),
            ],
            options={
                'verbose_name': 'Detalle de Atención',
                'verbose_name_plural': 'Detalles de Atención',
                'ordering': ['atencion'],
            },
        ),
        migrations.AddField(
            model_name='atencion',
            name='examenes_enviados',
            field=models.ManyToManyField(blank=True, related_name='atenciones_examenes', to='attention.examensolicitado', verbose_name='Exámenes Enviados'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Monto')),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('PayPal', 'PayPal')], max_length=50, verbose_name='Método de Pago')),
                ('pagado', models.BooleanField(default=False, verbose_name='Pagado')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('costo_atencion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='attention.costosatencion', verbose_name='Costo Atención')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='ServiciosAdicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=255, verbose_name='Nombre del Servicio')),
                ('costo_servicio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo del Servicio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Servicio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('costo_atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='attention.costosatencion', verbose_name='Costo Atención')),
            ],
            options={
                'verbose_name': 'Servicio Adicional',
                'verbose_name_plural': 'Servicios Adicionales',
                'ordering': ['nombre_servicio'],
            },
        ),
        migrations.CreateModel(
            name='CostoAtencionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_servicio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo del Servicio')),
                ('costo_atencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos_atenciones', to='attention.costosatencion', verbose_name='Costo Atención')),
                ('servicios_adicionales', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_adicionales', to='attention.serviciosadicionales', verbose_name='Servicios Adicionales')),
            ],
            options={
                'verbose_name': 'Costo detalle Atención',
                'verbose_name_plural': 'Costos detalles Atención',
            },
        ),
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la Cita')),
                ('hora_cita', models.TimeField(verbose_name='Hora de la Cita')),
                ('estado', models.CharField(choices=[('P', 'Programada'), ('C', 'Cancelada'), ('R', 'Realizada')], max_length=1, verbose_name='Estado de la Cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes_citas', to='core.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita Médica',
                'verbose_name_plural': 'Citas Médicas',
                'ordering': ['fecha', 'hora_cita'],
                'indexes': [models.Index(fields=['fecha', 'hora_cita'], name='idx_fecha_hora')],
            },
        ),
    ]
