# Generated by Django 5.1.3 on 2024-11-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0007_certificado_diagnostico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='examenes_enviados',
        ),
        migrations.AddField(
            model_name='atencion',
            name='examenes_enviados',
            field=models.ManyToManyField(blank=True, to='attention.examensolicitado', verbose_name='Exámenes Enviados'),
        ),
    ]
