# Generated by Django 5.1.3 on 2024-11-22 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0009_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.RemoveField(
            model_name='pago',
            name='examenes_medicos',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='servicios_adicionales',
        ),
        migrations.AddField(
            model_name='costosatencion',
            name='costo_consulta',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Costo de la Consulta'),
        ),
        migrations.AddField(
            model_name='costosatencion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de los Costos'),
        ),
        migrations.AddField(
            model_name='examensolicitado',
            name='atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examenes_solicitados', to='attention.atencion', verbose_name='Atención Médica'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='examenes_enviados',
            field=models.ManyToManyField(blank=True, related_name='atenciones_examenes', to='attention.examensolicitado', verbose_name='Exámenes Enviados'),
        ),
        migrations.AlterField(
            model_name='costosatencion',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(max_length=50, verbose_name='Método de Pago'),
        ),
    ]
