# Generated by Django 5.1.3 on 2024-11-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0010_alter_pago_options_remove_pago_examenes_medicos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('PayPal', 'PayPal')], max_length=50, verbose_name='Método de Pago'),
        ),
    ]
