# Generated by Django 5.1.3 on 2024-11-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0011_alter_pago_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Monto'),
        ),
    ]
