# Generated by Django 5.1.3 on 2024-11-22 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0012_alter_pago_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciosadicionales',
            name='costos_atenciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_adicionales', to='attention.costosatencion'),
        ),
    ]
