# Generated by Django 5.1.3 on 2024-11-22 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0013_serviciosadicionales_costos_atenciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciosadicionales',
            name='costos_atenciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_adicionales', to='attention.costosatencion'),
        ),
    ]
