# Generated by Django 5.1.3 on 2024-11-22 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0014_alter_serviciosadicionales_costos_atenciones'),
        ('core', '0010_alter_doctor_cedula_alter_empleado_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciosadicionales',
            name='costos_atenciones',
        ),
        migrations.AddField(
            model_name='serviciosadicionales',
            name='costo_atencion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='attention.costosatencion', verbose_name='Costo Atención'),
        ),
        migrations.AlterField(
            model_name='costosatencion',
            name='atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos', to='attention.atencion', verbose_name='Atención'),
        ),
        migrations.AlterField(
            model_name='detalleatencion',
            name='atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='attention.atencion', verbose_name='Atención'),
        ),
        migrations.AlterField(
            model_name='detalleatencion',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_atencion', to='core.medicamento', verbose_name='Medicamento'),
        ),
        migrations.AlterField(
            model_name='examensolicitado',
            name='atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examenes', to='attention.atencion', verbose_name='Atención Médica'),
        ),
        migrations.AlterField(
            model_name='examensolicitado',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examenes', to='core.paciente', verbose_name='Paciente'),
        ),
    ]
