# Generated by Django 5.1.3 on 2024-11-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0015_remove_serviciosadicionales_costos_atenciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costosatencion',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total'),
        ),
    ]
