# Generated by Django 5.1.3 on 2024-11-22 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0016_alter_costosatencion_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costosatencion',
            name='atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos', to='attention.atencion'),
        ),
    ]
