# Generated by Django 5.1.3 on 2024-11-22 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0017_alter_costosatencion_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleatencion',
            name='examen_solicitado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_atencion', to='attention.examensolicitado', verbose_name='Examen Solicitado'),
        ),
        migrations.AlterField(
            model_name='serviciosadicionales',
            name='costo_atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='attention.costosatencion', verbose_name='Costo Atención'),
        ),
    ]
