# Generated by Django 5.1.3 on 2024-11-22 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0018_detalleatencion_examen_solicitado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleatencion',
            name='examen_solicitado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_atencion', to='attention.examensolicitado', verbose_name='Examen Solicitado'),
        ),
    ]
