# Generated by Django 5.1.3 on 2024-11-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0019_alter_detalleatencion_examen_solicitado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleatencion',
            name='examen_solicitado',
        ),
    ]
