# Generated by Django 5.1.3 on 2024-11-22 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0020_remove_detalleatencion_examen_solicitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleatencion',
            name='examen_solicitado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_atencion', to='attention.examensolicitado', verbose_name='Examen Solicitado'),
        ),
    ]
